---
- name: Create ansible facts.d dir
  become: yes
  file:
    path: /etc/ansible/facts.d
    state: directory
    owner: root
    group: root
    mode: 0755
  tags: facts

- name: Create custom_facts
  become: yes
  ini_file:
    path: /etc/ansible/facts.d/custom_facts.fact
    section: "{{ item.0.section }}"
    option: "{{ item.1.key }}"
    value: "{{ item.1.value }}"
  with_subelements:
    - "{{ custom_facts }}"
    - settings
  tags: facts

- name: Re-read facts
  setup: filter=ansible_local
  tags: facts

- debug: msg="{{ ansible_local.custom_facts }}"
...
